enum ActionTypeKeys {
  GET_CURRENT_USER_INPROGRESS = "GET_CURRENT_USER_INPROGRESS",
  GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS",
  GET_CURRENT_USER_ERROR = "GET_CURRENT_USER_ERROR",
  GET_APP_STATE = "GET_APP_STATE",
  UPDATE_APP_STATE = "UPDATE_APP_STATE",
  ERROR_APP_STATE = "ERROR_APP_STATE",
}

export default ActionTypeKeys;
