
enum ActionTypeKeys {
    GET_CURRENT_USER_INPROGRESS = "GET_CURRENT_USER_INPROGRESS",
    GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS",
    GET_CURRENT_USER_ERROR = "GET_CURRENT_USER_ERROR",
  
}

export default ActionTypeKeys;